### ISSUE TITLE
Support NEAR's & ETH FT tokens as voting token

### ISSUE THREAD

**Issue by ilblackdragon** [near-daos/sputnik-dao-contract#10]
Currently DAO only supports voting with it's internal token for voting.
This is because it just uses internal balance without any cross contract calls to fetch state.

Even if we assume that we want to fetch the balance of the given user via cross contract call, this opens up potential issues that user just keep moving tokens from one account to another and vote with them.
To prevent that, tokens must be "frozen" in some way during the vote or alternatively if user moves their tokens - their vote gets nullified.

One option is that user must deposit the tokens into the DAO first to be able to vote (e.g. stake to participate in the governance).

What are other options to handle this?

**Comment by luciotato** [comment]
This is old, you may have solved this already, but my 2 cents:
Vote by staking sounds like the best option, but you need to:
* have the option to "un-vote(un-stake)" while proposal is "in process"
* store user & token amount in the proposal's voters' vec 
* cleanup-1: allow unstake-all, **if** the proposal is no longer "in-process" .- (anyone should be able to call this fn for any voter)
* cleanup-2: can't delete a proposal until all voters have unstaked (this is why anyone should be able to call the cleanup-1)
* extension for visibility: wait for 7 days from resolution until cleanup-1 & cleanup-2 can be called.
