### ISSUE TITLE
Add unit tests for the DAO factory 

### ISSUE THREAD

**Issue by ctindogaru** [near-daos/sputnik-dao-contract#106]
Increase unit test coverage of the factory: 

https://github.com/near-daos/sputnik-dao-contract/blob/main/sputnikdao-factory2/src/lib.rs

Every method should be tested with at least one happy scenario. Please also add a failure scenario where possible.

**Comment by TrevorJTClarke** [comment]
@ctindogaru This issue will need to address the requirements setup in #112 which will be complete soon.

**Comment by TrevorJTClarke** [comment]
@ctindogaru going to close this, in favor of the issues created to cover scenarios - see full kanban here: https://github.com/orgs/near-daos/projects/3/views/4
