### ISSUE TITLE
Create simulation/ava tests for proposal types that are not yet covered

### ISSUE THREAD

**Issue by ctindogaru** [near-daos/sputnik-dao-contract#107]
These are all the proposal types available in sputnik:
https://github.com/near-daos/sputnik-dao-contract/blob/main/sputnikdao2/src/proposals.rs#L59-L114

Not all of them are covered by simulation tests, so please take a look on the existing ones (https://github.com/near-daos/sputnik-dao-contract/blob/main/sputnikdao2/tests/test_general.rs) and try to cover all of them in the same way.

Lately, we are trying to use more `ava` testing. See example here: https://github.com/near-daos/sputnik-dao-contract/blob/main/sputnikdao2/tests-ava/__tests__/proposals.ava.ts

Any addition of simulation/ava tests is a plus 👍 .

**Comment by TrevorJTClarke** [comment]
@ctindogaru its on my immediate list to create the full coverage scope list, so i will assign to me until I can sort & create issues for everything.

**Comment by ctindogarus4f** [comment]
Hey @TrevorJTClarke, I have specifically created this issue for the devs that we are trying to onboard to the sputnik smart contracts. Please don't start working on this :) I will assign them to the issue

**Comment by TrevorJTClarke** [comment]
@ctindogaru you can follow the progress on this in the PR #112 - still working through all cases & contexts.
Once complete, i will create further issues that are broken down into sized tasks. Closing in favor of my workflow.
