### ISSUE TITLE
Official compiled wasm & CI/CD

### ISSUE THREAD

**Issue by TrevorJTClarke** [near-daos/sputnik-dao-contract#132]
To ensure audits, deploys & local builds are all reproducible, create a CI/CD pipeline that utilizes a docker build. This will ensure no user paths enter a build, destroying reproducibility.

**Comment by TrevorJTClarke** [comment]
https://hub.docker.com/r/nearprotocol/contract-builder

**Comment by swfsql** [comment]
Not related to docker, but this contract has an example of Github Actions on how to compile and share the wasm binaries: https://github.com/nearcomponents/contract-version-example/releases

**Comment by TrevorJTClarke** [comment]
@swfsql excellent - much better approach.

**Comment by swfsql** [comment]
@TrevorJTClarke Cool! in this way by making a tag those actions should make some release files

I'll make a PR containing some small improvements that we have observed
