### ISSUE TITLE
bug: if internal_execute_proposal fails, the proposal ends-up approved but not really executed

### ISSUE THREAD

**Issue by luciotato** [near-daos/sputnik-dao-contract#14]
internal_execute_proposal can include remote-upgrade & remote-call
if the Promise fails, the proposal ends-up approved but not executed

Proposed solution:) internal_execute_proposal should always return a Promise with a .then callback
and the proposal should be marked as Approved and the last vote counted only if the promise executed correctly

Security enhancement: For function calls the DAO should register target code hash and check before execution. (to avoid a code-swap attack before last vote)

**Comment by ilblackdragon** [comment]
Yep, I think if Promise failed - you need a new proposal, because running the same proposal again will lead to the same result.
