### ISSUE TITLE
Need assistance with deployment of a Sputnik-like DAO

### ISSUE THREAD

**Issue by siddharthborderwala** [near-daos/sputnik-dao-contract#140]
Hello,
I am Siddharth, a full stack web3 developer from [Crypto Capable](https://cryptocapable.community/), India. I am trying to deploy the smart contract for a DAO, having a subset of the features of sputnik. I am facing a problem during the Instantiation of the contract. The build scripts and the cargo.toml config are the exact same as sputnik.

I am passing this data to create a DAO but it is not working -
![image](https://user-images.githubusercontent.com/54456279/158392061-8b51fa95-fbab-4add-8cad-de7de85b4c31.png)
Link to the above transaction - https://explorer.testnet.near.org/transactions/8z1utD7PnhD7y1PN9uuTD4Lf3rbooQ5kvsh92U1TaYvF

This is what the error message looks like:
_Failure:_
```json
{
  "ActionError": {
    "index": 3,
    "kind": {
      "FunctionCallError": {
        "CompilationError": {
          "PrepareError": "Instantiate"
        }
      }
    }
  }
}
```
This is the function signature to instantiate the new DAO:
![image](https://user-images.githubusercontent.com/54456279/158391978-13164e8c-0fa9-4414-a9dd-3e44c84ad3c6.png)

It would be great if someone from the sputnik team can help me out. Even a pointer to the solution would be highly appreciated!

Sincerely
Siddharth Borderwala
Crypto Capable
India

**Comment by TrevorJTClarke** [comment]
Hi @siddharthborderwala  - interesting problem.
I suggest trying to use the official code for now (here is testnet deployed: https://testnet-v2.sputnik.fund/#/)
While we dont have customer service support for sputnik, I encourage you to checkout [Astro](https://astrodao.com/)

**Comment by siddharthborderwala** [comment]
Hello @TrevorJTClarke thanks a lot for the idea and your time. I kept digging at this problem and found out that using the [rand](https://crates.io/crates/rand) crate was causing this issue.

So, `rand` depends on [getrandom](https://crates.io/crates/getrandom) which does not support wasm-unknown-unknown in the near protocol EVMs. Hence, the compiled WASM Code was not able to Instantiate the Contract.

Now, I am instead using a custom secure random number generator and the contract instantiates without errors.
