### ISSUE TITLE
How to upload new code for upgraded smart contract/DAO

### ISSUE THREAD

**Issue by siddharthborderwala** [near-daos/sputnik-dao-contract#143]
I am trying to understand how to upgrade my dao. I think we can call upgrade_self, but I don't understand how and where to upload the new version of the code? Please help me out, thanks!

In this picture below (taken from sputnik-dao code itself), the function takes in a hash, I take it the hash is the hash generated by the system storage for the uploaded code. But I don't understand how to upload that code into the smart contract's system storage.

![image](https://user-images.githubusercontent.com/54456279/159503300-1a7625af-f88b-41a3-9064-efc262aa6ac4.png)

**Please help me out, thanks in advance!**

**Comment by TrevorJTClarke** [comment]
Hi @siddharthborderwala while the upgrade pieces are not live yet, if you have deployed your own factory / DAO, you can refer to this: https://github.com/near-daos/sputnik-dao-contract/blob/main/scripts/upgrade_dao_proposal_dev.sh

**Comment by siddharthborderwala** [comment]
Hello! Thanks for the pointer, it helped. The confusion is clear now!
