### ISSUE TITLE
ASTRO DAO missing action for voting only on polls

### ISSUE THREAD

**Issue by mutidao** [near-daos/sputnik-dao-contract#157]
I am looking for a cli commant which allows a specific group within the DAO to only vote on polls, not proposals/token transfers.
Currently only those seem to be available:

AddProposal - Adds given proposal to the DAO (this is the primary mechanism for getting things done).
RemoveProposal - Removes given proposal (this is used for immediate deletion in special cases).
VoteApprove - Votes to approve given proposal or bounty.
VoteReject - Votes to reject given proposal or bounty.
VoteRemove - Votes to remove given proposal or bounty (this may be because the proposal is spam or otherwise invalid).
Finalize - Finalizes proposal which is cancelled when proposal has expired (this action also returns funds).
MoveToHub - Moves a proposal to the hub (this is used to move a proposal into another DAO).

Anyone could help with that?

**Comment by ctindogaru** [comment]
Hey @mutidao, thanks for creating the issue.

Why is that something that cannot be achieved with the existing tools?

You basically need to use `AddProposal` with `ProposalKind::Vote` (stands for Poll). Then, after the proposal is created, you can simply use `VoteApprove` or `VoteReject` to cast your votes on that specific poll. Am I missing something?

**Comment by ctindogaru** [comment]
For adding the poll:

`near call <dao_account_id> add_proposal '{"proposal": {"description": "You should put the description of the poll here", "kind": "Vote"}}' --accountId <caller_id> --amount 1`

For casting votes:
`near call <dao_account_id> act_proposal '{"id": <proposal_id>, "action": "VoteApprove"}' --accountId <caller_id>` or
`near call <dao_account_id> act_proposal '{"id": <proposal_id>, "action": "VoteReject"}' --accountId <caller_id>`

**Comment by mutidao** [comment]
Thank you! In the meantime we got it set up with the help of someone. As the UI doesn't give that option yet and we do not come with a dev background, it took some testing but now it works: https://app.astrodao.com/dao/inav2.sputnik-dao.near/groups/all

Thanks for taking the time to respond!

**Comment by ctindogaru** [comment]
My pleasure, sorry for taking so long.
