### ISSUE TITLE
Successful bounty claimant doesn't get their bounty bond back

### ISSUE THREAD

**Issue by ReidWilliams** [near-daos/sputnik-dao-contract#19]
Tracing through the series of calls:

First, return _proposal_ bond, but this is different than the bounty bond right?
https://github.com/near-daos/sputnik-dao-contract/blob/c2cf1553b070d04eed8f659571440b27d398c588/sputnikdao2/src/proposals.rs#L271

Call `internal_execute_bounty_payout`
https://github.com/near-daos/sputnik-dao-contract/blob/c2cf1553b070d04eed8f659571440b27d398c588/sputnikdao2/src/proposals.rs#L345-L348

Bounty claimaint is paid the actual bounty, but I don't see the bond being returned
https://github.com/near-daos/sputnik-dao-contract/blob/c2cf1553b070d04eed8f659571440b27d398c588/sputnikdao2/src/bounties.rs#L77-L91

**Comment by mikedotexe** [comment]
Hey, great attention to detail here. So I believe that first part you linked is in fact sending the native NEAR back to person who created the proposal. After all, the kind of proposal we have here is `AddBounty` or `BountyDone`. Just to be clear, are you suggesting that one of those two is not returning the bond? Will keep digging in and would love to discuss

**Comment by ReidWilliams** [comment]
@mikedotexe that's right, it looks like when a user makes a `BountyDone` proposal that is accepted, they get their proposal bond back but they don't get their bounty bond back.

I'm realizing this may be an misunderstanding on my part of what is meant by `proposal_bond` and `bounty_bond` in the `Policy` struct. I assumed that a proposal bond and a `BountyDone` bond are distinct, meaning that when a user makes a `BountyDone` proposal, they must pay two bonds, one with the amount `proposal_bond` and another with the amount `bounty_bond`.

Perhaps instead it's that there is only ever a single bond paid such that:
- For all proposal types, the amount of the bond is `proposal_bond` *except*
- For proposal type `BountyDone` the amount of the bond is `bounty_bond`

**Comment by swfsql** [comment]
I believe that a change such as [this](https://github.com/mikedotexe/sputnik-dao-contract/pull/3/files#r752622201) would allow the bounty "done" proposal bond to be returned to the proposer  
@mikedotexe

**Comment by ctindogaru** [comment]
@ReidWilliams I think you're actually right.

The workflow is currently like this:

Someone adds an `AddBounty` proposal and must pay a **proposal bond**.
If proposal passes, a bounty gets created and people can claim on that bounty. Note that **proposal bond** is being returned to the `AddBounty` proposal creator.

Let's say a person is claiming on that specific bounty. They must pay a bounty bond.
There are 2 situations that can happen:
1. They can give up on the bounty => bounty bond gets returned to the claimer
2. They actually complete the bounty so they create a `BountyDone` proposal to claim the reward. They must pay a proposal bond. Note that they also paid a bounty bond and they are also paying a proposal bond.
If the proposal passes, they get the refund. The proposal bond is also being returned to the `BountyDone` proposal creator.
However, the bounty bond that was taken on the claim is never being returned and remains in the DAO.

Will create a PR to fix this.
