### ISSUE TITLE
Need ability to handle failed payouts

### ISSUE THREAD

**Issue by mikedotexe** [near-daos/sputnik-dao-contract#30]
Currently `Transfer` and `BountyDone` proposals have payouts that eventually hit the method `internal_payout`.

This method will attempt to pay out with native NEAR Ⓝ or a fungible token. In the case of fungible tokens, it uses cross-contract calls here:

https://github.com/near-daos/sputnik-dao-contract/blob/317ea4fb1e6eac8064ef29a78054b0586a3406c3/sputnikdao2/src/proposals.rs#L239-L260

Since there is no callback provided, the transfer might fail but the bounty is considered completed. There may be times where individuals forget to top up their fungible tokens and make an honest mistake that will confuse folks.

Ideally, if a fungible token transfer fails, we can have some way of letting it be known that this proposal needs more tokens to complete the transfer.

I think the best solution might be to add an item to the `ProposalStatus` enum, something like `PayoutFailed`.

In the case of a plain transfer (with `ft_transfer`) we'd simply check for a promise failure.
For the transfer-and-call functionality (with `ft_transfer_call`) we'll have to implement `ft_resolve_transfer` (see [Nomicon for details](https://nomicon.io/Standards/FungibleToken/Core.html#reference-level-explanation)) and ensure that the `amount` argument given is always `0`. We expect that the full bounty amount will always be transferred and none will be returned.

**Comment by ctindogaru** [comment]
This has been fixed in https://github.com/near-daos/sputnik-dao-contract/pull/61
