### ISSUE TITLE
Incorrect docs on `ProposalKind`

### ISSUE THREAD

**Issue by evergreen-trading-systems** [near-daos/sputnik-dao-contract#34]
Docs mention `mint` `as a proposal-kind` - https://github.com/near-daos/sputnik-dao-contract/tree/main/sputnikdao2#proposal-kinds

<img width="763" alt="Screenshot 2021-08-21 at 17 03 41" src="https://user-images.githubusercontent.com/4870868/130327870-fae0d46b-d75b-479e-9d3a-87fe0e8cea63.png">

Source code says otherwise - https://github.com/near-daos/sputnik-dao-contract/blob/main/sputnikdao2/src/proposals.rs#L48

<img width="403" alt="Screenshot 2021-08-21 at 17 04 59" src="https://user-images.githubusercontent.com/4870868/130327911-cdbe6701-a0cd-4c36-8126-a27c3d58e91e.png">

**Comment by ctindogaru** [comment]
This has been fixed recently.
