### ISSUE TITLE
publish to docs.rs

### ISSUE THREAD

**Issue by evergreen-trading-systems** [near-daos/sputnik-dao-contract#35]
Hackathon participant here

Can I fork this repo and publish to `docs.rs` in pr?

- It is so confusing read the source code on Github and follow.
- It is a headache to download the source code to machine, wait for IDE to cache and then follow types.

`docs.rs` is the best place for rust documentation and this would greatly improves developer experience here. Onboarding rust developers into smart-contract-development without that is not even viable in my opinion. Need a birds eye view on rust primitives and no good way to currently do that.

I'd modify the github ci workflow and cargo packages to achieve this. I'd need input from you on the cargo metadata. Apart from that I can send a pr?

If not I'd still push to `docs.rs`, it is needed.

**Comment by mikedotexe** [comment]
I'm not aware of any smart contracts that are crates, besides the NEAR Contract Standards, which is meant to be used as a dependency when building a project.

https://docs.rs/about
>Docs.rs is an open source documentation host for crates of the Rust Programming Language.

You may feel free to create a crate if you wish, for sure.

**Comment by swfsql** [comment]
It's also possible to have github actions to publish master's docs on Github Pages
