### ISSUE TITLE
v2 release feature set

### ISSUE THREAD

**Issue by ilblackdragon** [near-daos/sputnik-dao-contract#4]
"Hub" functionality on the factory contract:
 - [x] List of proposals and bounties as well
 - [ ] DAOs can pull from Hub and push proposals to Hub

New proposals types:
 - [x] Function call -- similar to multisig
 - [x] Poll: just voting on some question
 - [x] Transfer NEP-141 tokens
 - [x] New bounty
 - [x] Bounty XYZ is done
 - [x] Upgrade the Sputnik
 - [ ] Grace period change

New action types:
 - [x] Dismiss proposal -- instead of waiting for proposal to expire without voting, vote to dismiss it. This is different from rejecting which means that bond will be returned to the author.
 - [ ] Edit proposal -- allows to edit description and payout. This is useful when need to add things like discussion link or if the amount should be changed post discussion.
 - [ ] Push to "Hub" -- moves proposal into the factory
 - [ ] Pull from "Hub" -- moves proposal from the factory to this DAO

Upgradability:
 - [ ] New version of the contract goes into the factory
 - [x] Any of the specific instances can call upgrade proposal, which on passing requests new code from factory
 - [x] Supports migrating old data to new format.

Extend Policy:
 - [x] Add roles (e.g. "admin", "facilitator")
 - [x] Each role can have different threshold of voting for different proposal types and even different action types. Including defining who can do certain types of actions (#1)

This allows to have biggest membership list with different permissions, while still maintain smaller list of people who can make actions and decisions.

Token issuance:
 - [x] Set ticker, total balance and other parameters during DAO creation
 - [x] The initial amount is on the balance of the DAO itself (treasury) and needs be moved like others with proposals

One of the critical requirements is to make this code composable, so others can strip down features they don't need for their own version. E.g. token issuance is added as separate module and can be removed by removing few lines of code and trait implementation.

Note that all current DAOs will need to "exit" into new versions while keeping old names unusable.

**Comment by ethyuan** [comment]
set DAO token voting rights :
confirm council member 
authorize  (concil )token issue

**Comment by ilblackdragon** [comment]
Example of an advanced policy:
```

enum RoleKind {
   // Matches everyone else.
   Everyone,
   // Any authorized member.
   Member,
   // Authorized member with at least given weight.
   MemberWeight(u128),
   // Specific to given group name.
   Group(String),
   // Regex of account names. Can be used to restrict to some subset of sub-name.
   Regex(String),
}

struct GroupPermission {
   bond: u128,
   /// can_add_proposal, can_delete_proposal, can_change_policy, can_change_purpose, can_add_members, can_delete_members
   permissions: HashMap<String, bool>,
}

struct Policy {
   roles: HashMap<String, RolePermission>,
}

trait MemberList {
   fn get_groups(account_id: String) -> Vec<String>;
   fn member_weight(account_id: String) -> u128;
}

/// Returns permissions for given user, given policy and member list.
fn get_permissions(policy: &Policy, member_list: &dyn MemberList, account_id: String) -> GroupPermission {
   
}
```

**Comment by ilblackdragon** [comment]
Need to add next time locks:
 - period of proposal was voted and it can be finalized (this allows to prevent a bunch of attacks)
 - proposal expires

Smaller groups making decisions on smaller amounts is kind of harder to do in multitoken env.
Per token + per amount policy? Or just ask to create sub DAO and manage there smaller amount?

**Comment by ilblackdragon** [comment]
The decision to push "Hub" for v3 and focus on advanced policy and bounties.
Also v3 will just be an upgrade of v2, as now contract comes with self upgrade capability.

**Comment by GaloisField2718** [comment]
Hello, 

I've upgrade my DAO 
``` js
View call: genesisdao.anank2.testnet.get_proposal({"id":2})
{
  id: 2,
  proposer: 'anank2.testnet',
  description: 'Mise a jour du DAO en v3',
  kind: {
    UpgradeSelf: { hash: 'crHcQzdS4fVXJ5FZyybqDge3XAZT2mwgA9jMKCVicrT' }
  },
  status: 'Approved',
  vote_counts: { council: [ 3, 0, 0 ] },
  votes: {
    'anank1.testnet': 'Approve',
    'anank2.testnet': 'Approve',
    'anank3.testnet': 'Approve'
  },
  submission_time: '1652709295077317675'
}
```
And check it's done : 
``` bash
near view $DAO get_available_amount
View call: genesisdao.anank2.testnet.get_available_amount()
'5264085837604144200000000' 
```
But when I try to use some new functions like get_dao_list, I have this error : 
```js
View call: genesisdao.anank2.testnet.get_dao_list()
An error occured
Error: Querying [object Object] failed: wasm execution failed with error: FunctionCallError(MethodResolveError(MethodNotFound)).
{
  "block_hash": "Ekg1Fj2urHMCdSPAfXCrdiqRU2Wecm3fG9jVhNA6KQpc",
  "block_height": 90038371,
  "error": "wasm execution failed with error: FunctionCallError(MethodResolveError(MethodNotFound))",
  "logs": []
}
    at JsonRpcProvider.query (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:123:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Account.viewFunction (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:24)
    at async exports.callViewFunction (/usr/local/lib/node_modules/near-cli/index.js:94:48)
    at async Object.handler (/usr/local/lib/node_modules/near-cli/utils/exit-on-error.js:52:9)
TypedError: Querying [object Object] failed: wasm execution failed with error: FunctionCallError(MethodResolveError(MethodNotFound)).
{
  "block_hash": "Ekg1Fj2urHMCdSPAfXCrdiqRU2Wecm3fG9jVhNA6KQpc",
  "block_height": 90038371,
  "error": "wasm execution failed with error: FunctionCallError(MethodResolveError(MethodNotFound))",
  "logs": []
}
    at JsonRpcProvider.query (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:123:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Account.viewFunction (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:24)
    at async exports.callViewFunction (/usr/local/lib/node_modules/near-cli/index.js:94:48)
    at async Object.handler (/usr/local/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'UntypedError',
  context: undefined
}
```
It's like the method doesn't exist. 

How to solve this ? 
Upgrade again ? 

And especially is there specials argument to put inside command like get_dao_list ? If do, is there a doc for this arguments ?
