### ISSUE TITLE
Ensure payments with fungible tokens can attach storage_deposit

### ISSUE THREAD

**Issue by mikedotexe** [near-daos/sputnik-dao-contract#43]
![Screen Shot 2021-10-15 at 12 23 25 PM](https://user-images.githubusercontent.com/1042667/137541876-92161236-5fc1-431f-b3b3-f302f5ca3548.png)

My comment on this:

We should definitely fix that in the contract.

To have the smoothest experience while maintaining security for fungible tokens, the function would be have a Batch Action on the contract that does two function calls.
1. storage_deposit with the optional argument registration_only set to true
2. then transfer
If registration_only is set to true, it'll refund if the account is already paid for and not panic or block the transaction. Like this implementation:
https://github.com/near/near-sdk-rs/blob/95954cad746502aeb64e42a8bd5bbbb1ce0df8cc/near-contract-standards/src/fungible_token/storage_impl.rs#L45-L70

**Comment by ctindogaru** [comment]
I'm taking a look into this now.

**Comment by ctindogaru** [comment]
The issue has been addressed in https://github.com/near-daos/sputnik-dao-contract/pull/49.

However, it has been decided to solve this issue on Astro DAO side, instead of the Sputnik side, so that PR was closed.
