### ISSUE TITLE
Failed to create new DAO

### ISSUE THREAD

**Issue by nearmax** [near-daos/sputnik-dao-contract#5]
I have attempted to create a new DAO and it failed.

# Steps

* I filled out information in the DAO creation form for `devx.sputnikdao.near` DAO and pressed `Submit`.
* It redirected me to wallet where I approved the transfer of 30 NEAR;
* Wallet then showed the following error message:
![image](https://user-images.githubusercontent.com/35039879/107691722-aa044980-6c60-11eb-97f0-c5e54286ca74.png)
* When I went back to https://sputnik.fund/#/ I see  `devx.sputnikdao.near` DAO created without any information;
* When I try to select this DAO in sputnik DAO UI I get the following error message:
![image](https://user-images.githubusercontent.com/35039879/107691844-d4ee9d80-6c60-11eb-8e49-4336b74b27e6.png)

**Comment by DenysOf** [comment]
Failed transactions will be handled by https://github.com/near-daos/sputnik-dao-contract/issues/2 once implemented.

**Comment by nearmax** [comment]
Why did it fail in the first place?

My user flow seems to be standard for creating DAO, how else do you create DAO if this does not work?

**Comment by DenysOf** [comment]
> Why did it fail in the first place?
> 
> My user flow seems to be standard for creating DAO, how else do you create DAO if this does not work?

This, I'm not sure, you attached 30 deposit, which is acceptable, still the error was `LackBalanceForState ` meaning not enough deposit. Perhaps someone with better knowledge of the contract can advise.

**Comment by ilblackdragon** [comment]
You need 31.5 N right now - contract size is 315KB. @DenysOf can you update the minimum requirement in UI?

**Comment by ilblackdragon** [comment]
Duplicate with #21
Frontend should list correct deposit - https://github.com/near-daos/sputnik-dao-ui/issues/6

**Comment by DenysOf** [comment]
Changed on the frontend.
