### ISSUE TITLE
Failing test test_create_dao_and_use_token

### ISSUE THREAD

**Issue by mikedotexe** [near-daos/sputnik-dao-contract#55]
This test is failing on `main` right now it seems. I saw this by running `cargo test -- --nocapture` in the project root.

**Comment by ctindogaru** [comment]
I can confirm this, but the failure is non deterministic. Sometimes it does fail, sometimes it doesn't.

**Comment by ctindogaru** [comment]
This seems to be resolved on `main`.

Please reopen if you see it again, Mike.
