### ISSUE TITLE
Test "upgrade" functionality of the DAO

### ISSUE THREAD

**Issue by ctindogaru** [near-daos/sputnik-dao-contract#84]
Write simulation tests for the `upgrade` functionality. This functionality is critical but it lacks simulation tests. Note that it has been manually tested in https://github.com/near-daos/sputnik-dao-contract/pull/76 and it also has some unit tests, but that's not enough.

This was suggested in https://github.com/near-daos/sputnik-dao-contract/pull/69.

**Comment by TrevorJTClarke** [comment]
@ctindogaru is this fully complete? If so, please close

**Comment by ctindogaru** [comment]
Yes, we can close.
