### ISSUE TITLE
Add metadata when storing contract code

### ISSUE THREAD

**Issue by ctindogaru** [near-daos/sputnik-dao-contract#85]
This has been suggested in https://github.com/near-daos/sputnik-dao-contract/pull/69.

More precisely https://github.com/near-daos/sputnik-dao-contract/pull/69#issuecomment-1009925796.

**Comment by TrevorJTClarke** [comment]
@ctindogaru Adding some thoughts around this here: https://github.com/near-daos/sputnik-dao-contract/wiki/WIP:-DAO-Factory-&-Registry

**Comment by ctindogaru** [comment]
We can close this one, as it has been achieved. We need to reach a consensus on the versioning only.
