### ISSUE TITLE
Move everything related to sputnik v1 in a different repository

### ISSUE THREAD

**Issue by ctindogaru** [near-daos/sputnik-dao-contract#96]
All the smart contracts related to sputnik V1 should live in their own repository:
- they are no longer maintained
- to avoid confusion between sputnik V1 and sputnik V2
- to create a clear barrier between those 2

**Comment by starpause** [comment]
Definitely in favor of this to reduce confusion. Thanks!

**Comment by TrevorJTClarke** [comment]
I will work on a proposal for how this could work, so we can have archived versions remain public

**Comment by TrevorJTClarke** [comment]
@starpause @ctindogaru I propose the following to accomplish the above:

Steps:
- [ ] Create new repo "sputnik-legacy-contracts"
- [ ] Move [V1 Factory](https://github.com/near-daos/sputnik-dao-contract/tree/main/sputnikdao-factory) into sputnik-legacy-contracts
- [ ] Move [V1 DAO](https://github.com/near-daos/sputnik-dao-contract/tree/main/sputnikdao) into sputnik-legacy-contracts
- [ ] Add a note into sputnik-dao-contract README.md about the archived V1 code, noting that "sputnik-dao-contract" will remain the "evergreen" contract source. See factory & releases for individual versions.

If you agree, I will make this happen.

**Comment by ctindogaru** [comment]
Sounds good to me @TrevorJTClarke, thank you for this!

A few suggestions tho:
- I would keep the name of that repo very close to this one, so it will be very obvious for people what that repo is about. Maybe `sputnik-dao-contract-graveyard` or `sputnik-dao-contract-legacy`?
- Make sure that once you move everything in `sputnik-dao-contract-graveyard`, you will pull out the README inside `sputnikdao/README.md` and put it directly in the root.

Other than that, everything sounds good! Btw, you also make sure to decouple everything that's related to `sputnikdao` and `sputnikdao-factory` from this repo. I can only think about the building + the tests now.

**Comment by TrevorJTClarke** [comment]
NOTE: Added new repo: https://github.com/near-daos/sputnik-dao-contract-legacy

**Comment by TrevorJTClarke** [comment]
See PR: https://github.com/near-daos/sputnik-dao-contract/pull/103
That will finish this issue.
